/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    'site-settings': SiteSetting;
    'footer-links': FooterLink;
    about: About;
    contact: Contact;
    jobs: Job;
    pitch: Pitch;
    investors: Investor;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'footer-links': FooterLinksSelect<false> | FooterLinksSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    pitch: PitchSelect<false> | PitchSelect<true>;
    investors: InvestorsSelect<false> | InvestorsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  layout?:
    | (
        | {
            /**
             * Hero headline text. Line breaks are intentional.
             */
            heading: string;
            /**
             * Smaller subtext below the heading.
             */
            subtext?: string | null;
            /**
             * Static hero image (used for "default" and "split" variants).
             */
            media?: (number | null) | Media;
            variant: 'default' | 'split' | 'fullscreen' | 'slider-auto' | 'slider-curated';
            division: 'pictures-212' | 'pictures-310' | 'nrc' | 'corporate';
            /**
             * Crossfade duration in milliseconds (slider variants only).
             */
            fadeDuration?: number | null;
            /**
             * Time between slides in milliseconds (slider variants only).
             */
            autoplayDelay?: number | null;
            /**
             * Show the "01 / 04" slide indicator (slider variants only).
             */
            showIndicator?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * When enabled, all headings in this block use the massive display scale (e.g. "STORIES ACROSS GENERATIONS"). This separates visual size from semantic heading level.
             */
            megaScale?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            leftHeading: string;
            rightBody: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            ratio?: ('1-3' | '1-1' | '1-2') | null;
            alignment?: ('top' | 'center') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'twoCol';
          }
        | {
            heading?: string | null;
            items: {
              media?: (number | null) | Media;
              title?: string | null;
              description?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'grid';
          }
        | {
            heading: string;
            subtext?: string | null;
            buttons: {
              label: string;
              url: string;
              variant: 'solid' | 'ghost' | 'link';
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading?: string | null;
            layout: 'stacked' | 'carousel';
            quotes: {
              quote: string;
              attribution?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'quotes';
          }
        | {
            /**
             * Choose whether to manually curate tiles or pull from the Projects collection.
             */
            source: 'custom-media' | 'from-projects';
            /**
             * Filter projects by division (only when source = "from Projects").
             */
            projectFilter?: ('all' | '212' | '310' | 'nrc') | null;
            tiles?:
              | {
                  media: number | Media;
                  /**
                   * Short label shown below the tile.
                   */
                  caption?: string | null;
                  division?: ('none' | '212' | '310' | 'nrc') | null;
                  id?: string | null;
                }[]
              | null;
            showPerforations?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'filmstrip';
          }
        | {
            /**
             * Select the visual layout variant. Preview all at /dev/division-variants.
             */
            variant: 'v0-baseline' | 'v1-accordion' | 'v2-cards' | 'v3-split' | 'v4-timeline';
            /**
             * Optional section heading above the division rows. Line breaks are intentional.
             */
            heading?: string | null;
            /**
             * Optional subtext below the heading.
             */
            subtext?: string | null;
            divisions: {
              /**
               * Division name (e.g. "(212) Pictures").
               */
              name: string;
              colorToken:
                | '212-amber'
                | '212-sicilian-orange'
                | '310-imax'
                | 'nrc-grey'
                | '310-sicilian-blue'
                | 'nrc-navy';
              /**
               * Optional subtitle (e.g. "Brooklyn, New York").
               */
              subtitle?: string | null;
              /**
               * Division description body. Line breaks are intentional.
               */
              description?: string | null;
              /**
               * Optional image for variants that use media (v2-cards, v3-split).
               */
              media?: (number | null) | Media;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'divisionShowcase';
          }
        | {
            /**
             * Optional section heading. Line breaks are intentional.
             */
            heading?: string | null;
            columns: '2' | '3' | '4';
            stats: {
              /**
               * The large number or short text (e.g. "24", "$2.5M", "3x").
               */
              value: string;
              /**
               * Descriptive label below the value (e.g. "Projects in Development").
               */
              label: string;
              colorToken?:
                | (
                    | 'none'
                    | '212-amber'
                    | '212-sicilian-orange'
                    | '310-imax'
                    | 'nrc-grey'
                    | '310-sicilian-blue'
                    | 'nrc-navy'
                  )
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            /**
             * Text shown between the two rules (e.g. "Structure", "// DIVISIONS"). Leave blank for a plain rule.
             */
            label?: string | null;
            /**
             * Vertical padding around the divider.
             */
            spacing?: ('compact' | 'normal' | 'wide') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'divider';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Global identity, feature flags, and build metadata for APR 70 Pictures.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Short display name shown in the navigation and footer logotype.
   */
  brandLabel: string;
  /**
   * Full legal name used in the copyright notice.
   */
  legalEntity: string;
  /**
   * Short sub-headline used in meta descriptions and the footer.
   */
  tagline?: string | null;
  /**
   * Toggle the top and bottom sprocket-perforation rail chrome on every page.
   */
  showFilmstripRails?: boolean | null;
  /**
   * Timestamp of the last CI deploy.
   */
  lastDeployed?: string | null;
  /**
   * Semver of the last seed script run (e.g. "1.0.0").
   */
  seededVersion?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Navigation links displayed in the 4-column site footer grid.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-links".
 */
export interface FooterLink {
  id: number;
  /**
   * Column 1 — main site pages (Work, About, Investors, Contact, …).
   */
  primaryNav?:
    | {
        label: string;
        /**
         * e.g. /work or https://…
         */
        href: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Column 2 — links to division pages ((212), (310), NRC).
   */
  divisionNav?:
    | {
        label: string;
        href: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Column 3 — secondary links (Press, Careers, Pitch, News, …).
   */
  moreNav?:
    | {
        label: string;
        href: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  layout?:
    | (
        | {
            /**
             * Hero headline text. Line breaks are intentional.
             */
            heading: string;
            /**
             * Smaller subtext below the heading.
             */
            subtext?: string | null;
            /**
             * Static hero image (used for "default" and "split" variants).
             */
            media?: (number | null) | Media;
            variant: 'default' | 'split' | 'fullscreen' | 'slider-auto' | 'slider-curated';
            division: 'pictures-212' | 'pictures-310' | 'nrc' | 'corporate';
            /**
             * Crossfade duration in milliseconds (slider variants only).
             */
            fadeDuration?: number | null;
            /**
             * Time between slides in milliseconds (slider variants only).
             */
            autoplayDelay?: number | null;
            /**
             * Show the "01 / 04" slide indicator (slider variants only).
             */
            showIndicator?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * When enabled, all headings in this block use the massive display scale (e.g. "STORIES ACROSS GENERATIONS"). This separates visual size from semantic heading level.
             */
            megaScale?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            leftHeading: string;
            rightBody: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            ratio?: ('1-3' | '1-1' | '1-2') | null;
            alignment?: ('top' | 'center') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'twoCol';
          }
        | {
            heading?: string | null;
            items: {
              media?: (number | null) | Media;
              title?: string | null;
              description?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'grid';
          }
        | {
            heading: string;
            subtext?: string | null;
            buttons: {
              label: string;
              url: string;
              variant: 'solid' | 'ghost' | 'link';
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading?: string | null;
            layout: 'stacked' | 'carousel';
            quotes: {
              quote: string;
              attribution?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'quotes';
          }
        | {
            /**
             * Choose whether to manually curate tiles or pull from the Projects collection.
             */
            source: 'custom-media' | 'from-projects';
            /**
             * Filter projects by division (only when source = "from Projects").
             */
            projectFilter?: ('all' | '212' | '310' | 'nrc') | null;
            tiles?:
              | {
                  media: number | Media;
                  /**
                   * Short label shown below the tile.
                   */
                  caption?: string | null;
                  division?: ('none' | '212' | '310' | 'nrc') | null;
                  id?: string | null;
                }[]
              | null;
            showPerforations?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'filmstrip';
          }
        | {
            /**
             * Select the visual layout variant. Preview all at /dev/division-variants.
             */
            variant: 'v0-baseline' | 'v1-accordion' | 'v2-cards' | 'v3-split' | 'v4-timeline';
            /**
             * Optional section heading above the division rows. Line breaks are intentional.
             */
            heading?: string | null;
            /**
             * Optional subtext below the heading.
             */
            subtext?: string | null;
            divisions: {
              /**
               * Division name (e.g. "(212) Pictures").
               */
              name: string;
              colorToken:
                | '212-amber'
                | '212-sicilian-orange'
                | '310-imax'
                | 'nrc-grey'
                | '310-sicilian-blue'
                | 'nrc-navy';
              /**
               * Optional subtitle (e.g. "Brooklyn, New York").
               */
              subtitle?: string | null;
              /**
               * Division description body. Line breaks are intentional.
               */
              description?: string | null;
              /**
               * Optional image for variants that use media (v2-cards, v3-split).
               */
              media?: (number | null) | Media;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'divisionShowcase';
          }
        | {
            /**
             * Optional section heading. Line breaks are intentional.
             */
            heading?: string | null;
            columns: '2' | '3' | '4';
            stats: {
              /**
               * The large number or short text (e.g. "24", "$2.5M", "3x").
               */
              value: string;
              /**
               * Descriptive label below the value (e.g. "Projects in Development").
               */
              label: string;
              colorToken?:
                | (
                    | 'none'
                    | '212-amber'
                    | '212-sicilian-orange'
                    | '310-imax'
                    | 'nrc-grey'
                    | '310-sicilian-blue'
                    | 'nrc-navy'
                  )
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            /**
             * Text shown between the two rules (e.g. "Structure", "// DIVISIONS"). Leave blank for a plain rule.
             */
            label?: string | null;
            /**
             * Vertical padding around the divider.
             */
            spacing?: ('compact' | 'normal' | 'wide') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'divider';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  layout?:
    | (
        | {
            /**
             * Hero headline text. Line breaks are intentional.
             */
            heading: string;
            /**
             * Smaller subtext below the heading.
             */
            subtext?: string | null;
            /**
             * Static hero image (used for "default" and "split" variants).
             */
            media?: (number | null) | Media;
            variant: 'default' | 'split' | 'fullscreen' | 'slider-auto' | 'slider-curated';
            division: 'pictures-212' | 'pictures-310' | 'nrc' | 'corporate';
            /**
             * Crossfade duration in milliseconds (slider variants only).
             */
            fadeDuration?: number | null;
            /**
             * Time between slides in milliseconds (slider variants only).
             */
            autoplayDelay?: number | null;
            /**
             * Show the "01 / 04" slide indicator (slider variants only).
             */
            showIndicator?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * When enabled, all headings in this block use the massive display scale (e.g. "STORIES ACROSS GENERATIONS"). This separates visual size from semantic heading level.
             */
            megaScale?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            leftHeading: string;
            rightBody: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            ratio?: ('1-3' | '1-1' | '1-2') | null;
            alignment?: ('top' | 'center') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'twoCol';
          }
        | {
            heading?: string | null;
            items: {
              media?: (number | null) | Media;
              title?: string | null;
              description?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'grid';
          }
        | {
            heading: string;
            subtext?: string | null;
            buttons: {
              label: string;
              url: string;
              variant: 'solid' | 'ghost' | 'link';
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading?: string | null;
            layout: 'stacked' | 'carousel';
            quotes: {
              quote: string;
              attribution?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'quotes';
          }
        | {
            /**
             * Choose whether to manually curate tiles or pull from the Projects collection.
             */
            source: 'custom-media' | 'from-projects';
            /**
             * Filter projects by division (only when source = "from Projects").
             */
            projectFilter?: ('all' | '212' | '310' | 'nrc') | null;
            tiles?:
              | {
                  media: number | Media;
                  /**
                   * Short label shown below the tile.
                   */
                  caption?: string | null;
                  division?: ('none' | '212' | '310' | 'nrc') | null;
                  id?: string | null;
                }[]
              | null;
            showPerforations?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'filmstrip';
          }
        | {
            /**
             * Select the visual layout variant. Preview all at /dev/division-variants.
             */
            variant: 'v0-baseline' | 'v1-accordion' | 'v2-cards' | 'v3-split' | 'v4-timeline';
            /**
             * Optional section heading above the division rows. Line breaks are intentional.
             */
            heading?: string | null;
            /**
             * Optional subtext below the heading.
             */
            subtext?: string | null;
            divisions: {
              /**
               * Division name (e.g. "(212) Pictures").
               */
              name: string;
              colorToken:
                | '212-amber'
                | '212-sicilian-orange'
                | '310-imax'
                | 'nrc-grey'
                | '310-sicilian-blue'
                | 'nrc-navy';
              /**
               * Optional subtitle (e.g. "Brooklyn, New York").
               */
              subtitle?: string | null;
              /**
               * Division description body. Line breaks are intentional.
               */
              description?: string | null;
              /**
               * Optional image for variants that use media (v2-cards, v3-split).
               */
              media?: (number | null) | Media;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'divisionShowcase';
          }
        | {
            /**
             * Optional section heading. Line breaks are intentional.
             */
            heading?: string | null;
            columns: '2' | '3' | '4';
            stats: {
              /**
               * The large number or short text (e.g. "24", "$2.5M", "3x").
               */
              value: string;
              /**
               * Descriptive label below the value (e.g. "Projects in Development").
               */
              label: string;
              colorToken?:
                | (
                    | 'none'
                    | '212-amber'
                    | '212-sicilian-orange'
                    | '310-imax'
                    | 'nrc-grey'
                    | '310-sicilian-blue'
                    | 'nrc-navy'
                  )
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            /**
             * Text shown between the two rules (e.g. "Structure", "// DIVISIONS"). Leave blank for a plain rule.
             */
            label?: string | null;
            /**
             * Vertical padding around the divider.
             */
            spacing?: ('compact' | 'normal' | 'wide') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'divider';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  layout?:
    | (
        | {
            /**
             * Hero headline text. Line breaks are intentional.
             */
            heading: string;
            /**
             * Smaller subtext below the heading.
             */
            subtext?: string | null;
            /**
             * Static hero image (used for "default" and "split" variants).
             */
            media?: (number | null) | Media;
            variant: 'default' | 'split' | 'fullscreen' | 'slider-auto' | 'slider-curated';
            division: 'pictures-212' | 'pictures-310' | 'nrc' | 'corporate';
            /**
             * Crossfade duration in milliseconds (slider variants only).
             */
            fadeDuration?: number | null;
            /**
             * Time between slides in milliseconds (slider variants only).
             */
            autoplayDelay?: number | null;
            /**
             * Show the "01 / 04" slide indicator (slider variants only).
             */
            showIndicator?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * When enabled, all headings in this block use the massive display scale (e.g. "STORIES ACROSS GENERATIONS"). This separates visual size from semantic heading level.
             */
            megaScale?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            leftHeading: string;
            rightBody: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            ratio?: ('1-3' | '1-1' | '1-2') | null;
            alignment?: ('top' | 'center') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'twoCol';
          }
        | {
            heading?: string | null;
            items: {
              media?: (number | null) | Media;
              title?: string | null;
              description?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'grid';
          }
        | {
            heading: string;
            subtext?: string | null;
            buttons: {
              label: string;
              url: string;
              variant: 'solid' | 'ghost' | 'link';
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading?: string | null;
            layout: 'stacked' | 'carousel';
            quotes: {
              quote: string;
              attribution?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'quotes';
          }
        | {
            /**
             * Choose whether to manually curate tiles or pull from the Projects collection.
             */
            source: 'custom-media' | 'from-projects';
            /**
             * Filter projects by division (only when source = "from Projects").
             */
            projectFilter?: ('all' | '212' | '310' | 'nrc') | null;
            tiles?:
              | {
                  media: number | Media;
                  /**
                   * Short label shown below the tile.
                   */
                  caption?: string | null;
                  division?: ('none' | '212' | '310' | 'nrc') | null;
                  id?: string | null;
                }[]
              | null;
            showPerforations?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'filmstrip';
          }
        | {
            /**
             * Select the visual layout variant. Preview all at /dev/division-variants.
             */
            variant: 'v0-baseline' | 'v1-accordion' | 'v2-cards' | 'v3-split' | 'v4-timeline';
            /**
             * Optional section heading above the division rows. Line breaks are intentional.
             */
            heading?: string | null;
            /**
             * Optional subtext below the heading.
             */
            subtext?: string | null;
            divisions: {
              /**
               * Division name (e.g. "(212) Pictures").
               */
              name: string;
              colorToken:
                | '212-amber'
                | '212-sicilian-orange'
                | '310-imax'
                | 'nrc-grey'
                | '310-sicilian-blue'
                | 'nrc-navy';
              /**
               * Optional subtitle (e.g. "Brooklyn, New York").
               */
              subtitle?: string | null;
              /**
               * Division description body. Line breaks are intentional.
               */
              description?: string | null;
              /**
               * Optional image for variants that use media (v2-cards, v3-split).
               */
              media?: (number | null) | Media;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'divisionShowcase';
          }
        | {
            /**
             * Optional section heading. Line breaks are intentional.
             */
            heading?: string | null;
            columns: '2' | '3' | '4';
            stats: {
              /**
               * The large number or short text (e.g. "24", "$2.5M", "3x").
               */
              value: string;
              /**
               * Descriptive label below the value (e.g. "Projects in Development").
               */
              label: string;
              colorToken?:
                | (
                    | 'none'
                    | '212-amber'
                    | '212-sicilian-orange'
                    | '310-imax'
                    | 'nrc-grey'
                    | '310-sicilian-blue'
                    | 'nrc-navy'
                  )
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            /**
             * Text shown between the two rules (e.g. "Structure", "// DIVISIONS"). Leave blank for a plain rule.
             */
            label?: string | null;
            /**
             * Vertical padding around the divider.
             */
            spacing?: ('compact' | 'normal' | 'wide') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'divider';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pitch".
 */
export interface Pitch {
  id: number;
  layout?:
    | (
        | {
            /**
             * Hero headline text. Line breaks are intentional.
             */
            heading: string;
            /**
             * Smaller subtext below the heading.
             */
            subtext?: string | null;
            /**
             * Static hero image (used for "default" and "split" variants).
             */
            media?: (number | null) | Media;
            variant: 'default' | 'split' | 'fullscreen' | 'slider-auto' | 'slider-curated';
            division: 'pictures-212' | 'pictures-310' | 'nrc' | 'corporate';
            /**
             * Crossfade duration in milliseconds (slider variants only).
             */
            fadeDuration?: number | null;
            /**
             * Time between slides in milliseconds (slider variants only).
             */
            autoplayDelay?: number | null;
            /**
             * Show the "01 / 04" slide indicator (slider variants only).
             */
            showIndicator?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * When enabled, all headings in this block use the massive display scale (e.g. "STORIES ACROSS GENERATIONS"). This separates visual size from semantic heading level.
             */
            megaScale?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            leftHeading: string;
            rightBody: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            ratio?: ('1-3' | '1-1' | '1-2') | null;
            alignment?: ('top' | 'center') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'twoCol';
          }
        | {
            heading?: string | null;
            items: {
              media?: (number | null) | Media;
              title?: string | null;
              description?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'grid';
          }
        | {
            heading: string;
            subtext?: string | null;
            buttons: {
              label: string;
              url: string;
              variant: 'solid' | 'ghost' | 'link';
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading?: string | null;
            layout: 'stacked' | 'carousel';
            quotes: {
              quote: string;
              attribution?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'quotes';
          }
        | {
            /**
             * Choose whether to manually curate tiles or pull from the Projects collection.
             */
            source: 'custom-media' | 'from-projects';
            /**
             * Filter projects by division (only when source = "from Projects").
             */
            projectFilter?: ('all' | '212' | '310' | 'nrc') | null;
            tiles?:
              | {
                  media: number | Media;
                  /**
                   * Short label shown below the tile.
                   */
                  caption?: string | null;
                  division?: ('none' | '212' | '310' | 'nrc') | null;
                  id?: string | null;
                }[]
              | null;
            showPerforations?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'filmstrip';
          }
        | {
            /**
             * Select the visual layout variant. Preview all at /dev/division-variants.
             */
            variant: 'v0-baseline' | 'v1-accordion' | 'v2-cards' | 'v3-split' | 'v4-timeline';
            /**
             * Optional section heading above the division rows. Line breaks are intentional.
             */
            heading?: string | null;
            /**
             * Optional subtext below the heading.
             */
            subtext?: string | null;
            divisions: {
              /**
               * Division name (e.g. "(212) Pictures").
               */
              name: string;
              colorToken:
                | '212-amber'
                | '212-sicilian-orange'
                | '310-imax'
                | 'nrc-grey'
                | '310-sicilian-blue'
                | 'nrc-navy';
              /**
               * Optional subtitle (e.g. "Brooklyn, New York").
               */
              subtitle?: string | null;
              /**
               * Division description body. Line breaks are intentional.
               */
              description?: string | null;
              /**
               * Optional image for variants that use media (v2-cards, v3-split).
               */
              media?: (number | null) | Media;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'divisionShowcase';
          }
        | {
            /**
             * Optional section heading. Line breaks are intentional.
             */
            heading?: string | null;
            columns: '2' | '3' | '4';
            stats: {
              /**
               * The large number or short text (e.g. "24", "$2.5M", "3x").
               */
              value: string;
              /**
               * Descriptive label below the value (e.g. "Projects in Development").
               */
              label: string;
              colorToken?:
                | (
                    | 'none'
                    | '212-amber'
                    | '212-sicilian-orange'
                    | '310-imax'
                    | 'nrc-grey'
                    | '310-sicilian-blue'
                    | 'nrc-navy'
                  )
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            /**
             * Text shown between the two rules (e.g. "Structure", "// DIVISIONS"). Leave blank for a plain rule.
             */
            label?: string | null;
            /**
             * Vertical padding around the divider.
             */
            spacing?: ('compact' | 'normal' | 'wide') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'divider';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investors".
 */
export interface Investor {
  id: number;
  layout?:
    | (
        | {
            /**
             * Hero headline text. Line breaks are intentional.
             */
            heading: string;
            /**
             * Smaller subtext below the heading.
             */
            subtext?: string | null;
            /**
             * Static hero image (used for "default" and "split" variants).
             */
            media?: (number | null) | Media;
            variant: 'default' | 'split' | 'fullscreen' | 'slider-auto' | 'slider-curated';
            division: 'pictures-212' | 'pictures-310' | 'nrc' | 'corporate';
            /**
             * Crossfade duration in milliseconds (slider variants only).
             */
            fadeDuration?: number | null;
            /**
             * Time between slides in milliseconds (slider variants only).
             */
            autoplayDelay?: number | null;
            /**
             * Show the "01 / 04" slide indicator (slider variants only).
             */
            showIndicator?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * When enabled, all headings in this block use the massive display scale (e.g. "STORIES ACROSS GENERATIONS"). This separates visual size from semantic heading level.
             */
            megaScale?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            leftHeading: string;
            rightBody: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            ratio?: ('1-3' | '1-1' | '1-2') | null;
            alignment?: ('top' | 'center') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'twoCol';
          }
        | {
            heading?: string | null;
            items: {
              media?: (number | null) | Media;
              title?: string | null;
              description?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'grid';
          }
        | {
            heading: string;
            subtext?: string | null;
            buttons: {
              label: string;
              url: string;
              variant: 'solid' | 'ghost' | 'link';
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            heading?: string | null;
            layout: 'stacked' | 'carousel';
            quotes: {
              quote: string;
              attribution?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'quotes';
          }
        | {
            /**
             * Choose whether to manually curate tiles or pull from the Projects collection.
             */
            source: 'custom-media' | 'from-projects';
            /**
             * Filter projects by division (only when source = "from Projects").
             */
            projectFilter?: ('all' | '212' | '310' | 'nrc') | null;
            tiles?:
              | {
                  media: number | Media;
                  /**
                   * Short label shown below the tile.
                   */
                  caption?: string | null;
                  division?: ('none' | '212' | '310' | 'nrc') | null;
                  id?: string | null;
                }[]
              | null;
            showPerforations?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'filmstrip';
          }
        | {
            /**
             * Select the visual layout variant. Preview all at /dev/division-variants.
             */
            variant: 'v0-baseline' | 'v1-accordion' | 'v2-cards' | 'v3-split' | 'v4-timeline';
            /**
             * Optional section heading above the division rows. Line breaks are intentional.
             */
            heading?: string | null;
            /**
             * Optional subtext below the heading.
             */
            subtext?: string | null;
            divisions: {
              /**
               * Division name (e.g. "(212) Pictures").
               */
              name: string;
              colorToken:
                | '212-amber'
                | '212-sicilian-orange'
                | '310-imax'
                | 'nrc-grey'
                | '310-sicilian-blue'
                | 'nrc-navy';
              /**
               * Optional subtitle (e.g. "Brooklyn, New York").
               */
              subtitle?: string | null;
              /**
               * Division description body. Line breaks are intentional.
               */
              description?: string | null;
              /**
               * Optional image for variants that use media (v2-cards, v3-split).
               */
              media?: (number | null) | Media;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'divisionShowcase';
          }
        | {
            /**
             * Optional section heading. Line breaks are intentional.
             */
            heading?: string | null;
            columns: '2' | '3' | '4';
            stats: {
              /**
               * The large number or short text (e.g. "24", "$2.5M", "3x").
               */
              value: string;
              /**
               * Descriptive label below the value (e.g. "Projects in Development").
               */
              label: string;
              colorToken?:
                | (
                    | 'none'
                    | '212-amber'
                    | '212-sicilian-orange'
                    | '310-imax'
                    | 'nrc-grey'
                    | '310-sicilian-blue'
                    | 'nrc-navy'
                  )
                | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            /**
             * Text shown between the two rules (e.g. "Structure", "// DIVISIONS"). Leave blank for a plain rule.
             */
            label?: string | null;
            /**
             * Vertical padding around the divider.
             */
            spacing?: ('compact' | 'normal' | 'wide') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'divider';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subtext?: T;
              media?: T;
              variant?: T;
              division?: T;
              fadeDuration?: T;
              autoplayDelay?: T;
              showIndicator?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              megaScale?: T;
              id?: T;
              blockName?: T;
            };
        twoCol?:
          | T
          | {
              leftHeading?: T;
              rightBody?: T;
              ratio?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        grid?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    media?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              subtext?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quotes?:
          | T
          | {
              heading?: T;
              layout?: T;
              quotes?:
                | T
                | {
                    quote?: T;
                    attribution?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        filmstrip?:
          | T
          | {
              source?: T;
              projectFilter?: T;
              tiles?:
                | T
                | {
                    media?: T;
                    caption?: T;
                    division?: T;
                    id?: T;
                  };
              showPerforations?: T;
              id?: T;
              blockName?: T;
            };
        divisionShowcase?:
          | T
          | {
              variant?: T;
              heading?: T;
              subtext?: T;
              divisions?:
                | T
                | {
                    name?: T;
                    colorToken?: T;
                    subtitle?: T;
                    description?: T;
                    media?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?: T;
              columns?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    colorToken?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        divider?:
          | T
          | {
              label?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandLabel?: T;
  legalEntity?: T;
  tagline?: T;
  showFilmstripRails?: T;
  lastDeployed?: T;
  seededVersion?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-links_select".
 */
export interface FooterLinksSelect<T extends boolean = true> {
  primaryNav?:
    | T
    | {
        label?: T;
        href?: T;
        openInNewTab?: T;
        id?: T;
      };
  divisionNav?:
    | T
    | {
        label?: T;
        href?: T;
        openInNewTab?: T;
        id?: T;
      };
  moreNav?:
    | T
    | {
        label?: T;
        href?: T;
        openInNewTab?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subtext?: T;
              media?: T;
              variant?: T;
              division?: T;
              fadeDuration?: T;
              autoplayDelay?: T;
              showIndicator?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              megaScale?: T;
              id?: T;
              blockName?: T;
            };
        twoCol?:
          | T
          | {
              leftHeading?: T;
              rightBody?: T;
              ratio?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        grid?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    media?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              subtext?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quotes?:
          | T
          | {
              heading?: T;
              layout?: T;
              quotes?:
                | T
                | {
                    quote?: T;
                    attribution?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        filmstrip?:
          | T
          | {
              source?: T;
              projectFilter?: T;
              tiles?:
                | T
                | {
                    media?: T;
                    caption?: T;
                    division?: T;
                    id?: T;
                  };
              showPerforations?: T;
              id?: T;
              blockName?: T;
            };
        divisionShowcase?:
          | T
          | {
              variant?: T;
              heading?: T;
              subtext?: T;
              divisions?:
                | T
                | {
                    name?: T;
                    colorToken?: T;
                    subtitle?: T;
                    description?: T;
                    media?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?: T;
              columns?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    colorToken?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        divider?:
          | T
          | {
              label?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subtext?: T;
              media?: T;
              variant?: T;
              division?: T;
              fadeDuration?: T;
              autoplayDelay?: T;
              showIndicator?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              megaScale?: T;
              id?: T;
              blockName?: T;
            };
        twoCol?:
          | T
          | {
              leftHeading?: T;
              rightBody?: T;
              ratio?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        grid?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    media?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              subtext?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quotes?:
          | T
          | {
              heading?: T;
              layout?: T;
              quotes?:
                | T
                | {
                    quote?: T;
                    attribution?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        filmstrip?:
          | T
          | {
              source?: T;
              projectFilter?: T;
              tiles?:
                | T
                | {
                    media?: T;
                    caption?: T;
                    division?: T;
                    id?: T;
                  };
              showPerforations?: T;
              id?: T;
              blockName?: T;
            };
        divisionShowcase?:
          | T
          | {
              variant?: T;
              heading?: T;
              subtext?: T;
              divisions?:
                | T
                | {
                    name?: T;
                    colorToken?: T;
                    subtitle?: T;
                    description?: T;
                    media?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?: T;
              columns?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    colorToken?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        divider?:
          | T
          | {
              label?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subtext?: T;
              media?: T;
              variant?: T;
              division?: T;
              fadeDuration?: T;
              autoplayDelay?: T;
              showIndicator?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              megaScale?: T;
              id?: T;
              blockName?: T;
            };
        twoCol?:
          | T
          | {
              leftHeading?: T;
              rightBody?: T;
              ratio?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        grid?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    media?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              subtext?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quotes?:
          | T
          | {
              heading?: T;
              layout?: T;
              quotes?:
                | T
                | {
                    quote?: T;
                    attribution?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        filmstrip?:
          | T
          | {
              source?: T;
              projectFilter?: T;
              tiles?:
                | T
                | {
                    media?: T;
                    caption?: T;
                    division?: T;
                    id?: T;
                  };
              showPerforations?: T;
              id?: T;
              blockName?: T;
            };
        divisionShowcase?:
          | T
          | {
              variant?: T;
              heading?: T;
              subtext?: T;
              divisions?:
                | T
                | {
                    name?: T;
                    colorToken?: T;
                    subtitle?: T;
                    description?: T;
                    media?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?: T;
              columns?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    colorToken?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        divider?:
          | T
          | {
              label?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pitch_select".
 */
export interface PitchSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subtext?: T;
              media?: T;
              variant?: T;
              division?: T;
              fadeDuration?: T;
              autoplayDelay?: T;
              showIndicator?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              megaScale?: T;
              id?: T;
              blockName?: T;
            };
        twoCol?:
          | T
          | {
              leftHeading?: T;
              rightBody?: T;
              ratio?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        grid?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    media?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              subtext?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quotes?:
          | T
          | {
              heading?: T;
              layout?: T;
              quotes?:
                | T
                | {
                    quote?: T;
                    attribution?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        filmstrip?:
          | T
          | {
              source?: T;
              projectFilter?: T;
              tiles?:
                | T
                | {
                    media?: T;
                    caption?: T;
                    division?: T;
                    id?: T;
                  };
              showPerforations?: T;
              id?: T;
              blockName?: T;
            };
        divisionShowcase?:
          | T
          | {
              variant?: T;
              heading?: T;
              subtext?: T;
              divisions?:
                | T
                | {
                    name?: T;
                    colorToken?: T;
                    subtitle?: T;
                    description?: T;
                    media?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?: T;
              columns?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    colorToken?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        divider?:
          | T
          | {
              label?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "investors_select".
 */
export interface InvestorsSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subtext?: T;
              media?: T;
              variant?: T;
              division?: T;
              fadeDuration?: T;
              autoplayDelay?: T;
              showIndicator?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              megaScale?: T;
              id?: T;
              blockName?: T;
            };
        twoCol?:
          | T
          | {
              leftHeading?: T;
              rightBody?: T;
              ratio?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        grid?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    media?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              heading?: T;
              subtext?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    url?: T;
                    variant?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        quotes?:
          | T
          | {
              heading?: T;
              layout?: T;
              quotes?:
                | T
                | {
                    quote?: T;
                    attribution?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        filmstrip?:
          | T
          | {
              source?: T;
              projectFilter?: T;
              tiles?:
                | T
                | {
                    media?: T;
                    caption?: T;
                    division?: T;
                    id?: T;
                  };
              showPerforations?: T;
              id?: T;
              blockName?: T;
            };
        divisionShowcase?:
          | T
          | {
              variant?: T;
              heading?: T;
              subtext?: T;
              divisions?:
                | T
                | {
                    name?: T;
                    colorToken?: T;
                    subtitle?: T;
                    description?: T;
                    media?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?: T;
              columns?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    colorToken?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        divider?:
          | T
          | {
              label?: T;
              spacing?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}