/**
 * backfill-ai-mark.ts — set the stored AI Mark flag on Media (idempotent).
 *
 * Why this exists
 * ---------------
 * Until 2026-09-07 the site decided a frame was AI-generated by matching the
 * English phrase "AI-generated" in the caption or credit printed beside it
 * (`/ai[\s-]?generated/i`, in web/src/components/v9/media.ts and
 * web/src/components/islands/FilmstripSlideshow.tsx). That rule dies the moment
 * a caption is written in Portuguese: the disclosure stamp would silently stop
 * appearing, which is a compliance failure, not a cosmetic one.
 *
 * The disclosure is a fact about the picture, so it now lives on the picture:
 * `Media.aiFrame`. This script reads every place a caption or credit is written
 * next to a media reference — the twelve v9 section blocks on the five page
 * globals, and every Project gallery plate and hero — applies the OLD regex to
 * that English text, and ticks `aiFrame` on the Media documents it names.
 *
 * It only ever turns the flag ON. A frame Marco has ticked by hand, or one whose
 * caption has since been translated, is never un-ticked by a re-run.
 *
 * Run from cms/:
 *   pnpm aimark:dry     (tsx scripts/backfill-ai-mark.ts --dry-run)
 *   pnpm aimark:apply   (tsx scripts/backfill-ai-mark.ts --apply)
 */

import 'dotenv/config'

// ── CLI + safety guards ──────────────────────────────────────────────────────

const APPLY = process.argv.includes('--apply')
const DRY = process.argv.includes('--dry-run')
if (APPLY === DRY) {
  console.error('backfill-ai-mark: pass exactly one of --dry-run or --apply. No changes made.')
  process.exit(1)
}

/** The historical rule, kept verbatim from web/src/components/v9/media.ts. */
const AI_TEXT = /ai[\s-]?generated/i
const isAiText = (...parts: Array<string | null | undefined>): boolean =>
  AI_TEXT.test(parts.filter(Boolean).join(' '))

/** Media references arrive as an id or as a populated doc, depending on depth. */
const mediaId = (value: unknown): number | null => {
  if (typeof value === 'number') return value
  if (typeof value === 'string' && /^\d+$/.test(value)) return Number(value)
  if (value && typeof value === 'object') {
    const id = (value as { id?: unknown }).id
    if (typeof id === 'number') return id
    if (typeof id === 'string' && /^\d+$/.test(id)) return Number(id)
  }
  return null
}

const V9_PAGE_SLUGS = ['v9-home', 'v9-slate', 'v9-craft', 'v9-methods', 'v9-contact'] as const

async function main(): Promise<void> {
  if (!process.env.DATABASE_URL) {
    console.error('backfill-ai-mark: DATABASE_URL not set. No changes made.')
    process.exit(1)
  }

  const { getPayload } = await import('payload')
  const { default: config } = await import('../src/payload.config.js')
  // Local API used loosely typed: block shapes mirror src/blocks/v9Sections.ts.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const payload = (await getPayload({ config })) as any

  /** media id -> the caption/credit line that convicted it (for the dry-run list). */
  const flagged = new Map<number, string>()
  const convict = (image: unknown, ...text: Array<string | null | undefined>) => {
    const id = mediaId(image)
    if (id === null || !isAiText(...text)) return
    if (!flagged.has(id)) flagged.set(id, text.filter(Boolean).join(' | ').slice(0, 120))
  }

  // ── 1. The five v9 page globals — every block that pairs media with a caption ──
  // Read in the default locale: the regex is an English rule, and English is
  // where the pre-i18n captions live.
  for (const slug of V9_PAGE_SLUGS) {
    const page = await payload.findGlobal({ slug, depth: 0, locale: 'en' })
    for (const section of page?.sections ?? []) {
      switch (section.blockType) {
        case 'photoFold':
        case 'archival':
          convict(section.image, section.caption, section.credit)
          break
        case 'moodGrid':
          for (const item of section.items ?? []) convict(item.image, item.caption, item.credit)
          break
        default:
          break
      }
    }
  }

  // ── 2. Every Project — gallery plates and the hero fold ──────────────────────
  const projects = await payload.find({
    collection: 'projects',
    limit: 1000,
    depth: 0,
    locale: 'en',
  })
  for (const project of projects.docs ?? []) {
    convict(project.heroImage, project.heroCaption, project.heroCredit)
    for (const plate of project.gallery ?? []) convict(plate.image, plate.caption, plate.credit)
    // Legacy v4 layout blocks can still carry filmstrip tiles with captions.
    for (const block of project.layout ?? []) {
      if (block.blockType === 'filmstrip') {
        for (const tile of block.tiles ?? []) convict(tile.media, tile.caption)
      }
    }
  }

  // ── 3. Apply, skipping media already flagged ────────────────────────────────
  const ids = [...flagged.keys()].sort((a, b) => a - b)
  const alreadySet: number[] = []
  const toSet: number[] = []
  for (const id of ids) {
    const doc = await payload.findByID({ collection: 'media', id, depth: 0 }).catch(() => null)
    if (!doc) continue
    if (doc.aiFrame === true) alreadySet.push(id)
    else toSet.push(id)
  }

  if (APPLY) {
    for (const id of toSet) {
      await payload.update({ collection: 'media', id, data: { aiFrame: true } })
    }
  }

  const total = await payload.count({ collection: 'media' })
  console.log(`\nbackfill-ai-mark — ${DRY ? 'DRY RUN (no writes)' : 'APPLIED'}`)
  console.log('────────────────────────────────────────────')
  console.log(`media in library     : ${total.totalDocs}`)
  console.log(`matched the AI rule  : ${ids.length}`)
  console.log(`already flagged      : ${alreadySet.length}`)
  console.log(`${DRY ? 'would flag' : 'newly flagged'}            : ${toSet.length}`)
  for (const id of toSet) console.log(`  + media ${id} — ${flagged.get(id)}`)
  process.exit(0)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
